### ISSUE TITLE
Warnings in JS console

### ISSUE THREAD

**Issue by JonniK** [priyatam/ringo#4]
Hello. I'm new in clojurescript and Om.
When i start new project based on this template i see this warnings in console:

> Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead
> 
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <header>. See https://fb.me/react-warning-keys for more information
> 
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the top-level render call using <ul>. See https://fb.me/react-warning-keys for more information
> 
> Warning: React.unmountComponentAtNode is deprecated. Please use ReactDOM.unmountComponentAtNode from require('react-dom') instead.

How can i fix it?

**Comment by ghost** [comment]
This is old but... You have to include an attribute of `key` on your html elements.

**Comment by JonniK** [comment]
Thanks, I already figured it out.
